version: '3.1'

services:
  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DATABASE_DATABASE}"
      MARIADB_USER: "${DATABASE_USER}"
      MARIADB_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - communityknowledge
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_PORT: 3306
      PMA_HOST: database
      PMA_USER: "${DATABASE_USER}"
      PMA_PASSWORD: "${DATABASE_PASSWORD}"
    networks:
      - communityknowledge


networks:
  communityknowledge:
    driver: bridge